//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTEGOLEntities2 : DbContext
    {
        public CTEGOLEntities2()
            : base("name=CTEGOLEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbcte> tbctes { get; set; }
        public virtual DbSet<tbctecancel> tbctecancels { get; set; }
        public virtual DbSet<tbctedocument> tbctedocuments { get; set; }
        public virtual DbSet<tbCTeEvento> tbCTeEventoes { get; set; }
        public virtual DbSet<tbcteinut> tbcteinuts { get; set; }
        public virtual DbSet<tbcteref> tbcterefs { get; set; }
        public virtual DbSet<tbDefinition> tbDefinitions { get; set; }
        public virtual DbSet<tbLog> tbLogs { get; set; }
        public virtual DbSet<tbmdfe> tbmdfes { get; set; }
        public virtual DbSet<tbmdfecancel> tbmdfecancels { get; set; }
        public virtual DbSet<tbMigrationFile1> tbMigrationFile1 { get; set; }
        public virtual DbSet<tbMigrationFile8> tbMigrationFile8 { get; set; }
        public virtual DbSet<tbMigrationTeste> tbMigrationTestes { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipios { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
        public virtual DbSet<tbcteCargaEspecial> tbcteCargaEspecials { get; set; }
        public virtual DbSet<tbcteemail> tbcteemails { get; set; }
        public virtual DbSet<tbCTeEventoDocument> tbCTeEventoDocuments { get; set; }
        public virtual DbSet<tbCTeEventoProcess> tbCTeEventoProcesses { get; set; }
        public virtual DbSet<tbCTeEventoRetorno> tbCTeEventoRetornoes { get; set; }
        public virtual DbSet<tbcteLog> tbcteLogs { get; set; }
        public virtual DbSet<tbcteprocess> tbcteprocesses { get; set; }
        public virtual DbSet<tbctereceptionhistory> tbctereceptionhistories { get; set; }
        public virtual DbSet<tbcteRetorno> tbcteRetornoes { get; set; }
        public virtual DbSet<tbcteRetornoInut> tbcteRetornoInuts { get; set; }
        public virtual DbSet<tbEstado> tbEstadoes { get; set; }
        public virtual DbSet<tbmdfeColdFile> tbmdfeColdFiles { get; set; }
        public virtual DbSet<tbmdfedamdfe> tbmdfedamdfes { get; set; }
        public virtual DbSet<tbmdfedetalhe> tbmdfedetalhes { get; set; }
        public virtual DbSet<tbmdfedocument> tbmdfedocuments { get; set; }
        public virtual DbSet<tbmdfeprintrequest> tbmdfeprintrequests { get; set; }
        public virtual DbSet<tbmdfeprocess> tbmdfeprocesses { get; set; }
        public virtual DbSet<tbmdfereceptionhistory> tbmdfereceptionhistories { get; set; }
        public virtual DbSet<tbmdfereceptionhistoryBKP> tbmdfereceptionhistoryBKPs { get; set; }
        public virtual DbSet<tbmdfeRetorno> tbmdfeRetornoes { get; set; }
    }
}
