//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcteLog
    {
        public long idCte { get; set; }
        public string evento { get; set; }
        public string dataEvento { get; set; }
        public string horaEvento { get; set; }
        public string tipoMsg { get; set; }
        public string msg { get; set; }
    }
}
