//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCTeEventoDocument
    {
        public long idCTeEvento { get; set; }
        public byte[] documentCabec { get; set; }
        public byte[] documentCTeOriginal { get; set; }
        public byte[] documentData { get; set; }
        public byte[] documentEvento { get; set; }
        public Nullable<System.DateTime> interfaceSendingDate { get; set; }
        public Nullable<System.DateTime> MASTERSAFSENDINGDATE { get; set; }
    
        public virtual tbCTeEvento tbCTeEvento { get; set; }
    }
}
