//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcteemail
    {
        public string CPFCNPJ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public int Id_Email { get; set; }
        public string userUpdate { get; set; }
        public string userCreate { get; set; }
        public string status { get; set; }
    }
}
