//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcteRetornoInut
    {
        public long idcte { get; set; }
        public byte[] documentRetCTE { get; set; }
        public Nullable<long> statusCTe { get; set; }
        public Nullable<long> XMLRETORNODate { get; set; }
        public Nullable<long> XMLRETORNOHHMM { get; set; }
        public Nullable<long> processDate { get; set; }
        public Nullable<long> processHHMM { get; set; }
    
        public virtual tbcteinut tbcteinut { get; set; }
    }
}
