//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCTeEvento
    {
        public long idCTeEvento { get; set; }
        public string clientId { get; set; }
        public Nullable<long> erpCode { get; set; }
        public Nullable<short> serie { get; set; }
        public Nullable<long> counterId { get; set; }
        public string eKey { get; set; }
        public Nullable<long> protocolNumber { get; set; }
        public Nullable<System.DateTime> processDate { get; set; }
        public string processMessage { get; set; }
        public Nullable<short> statusProcess { get; set; }
        public Nullable<short> statusCTe { get; set; }
        public string station { get; set; }
        public string cnpj { get; set; }
        public Nullable<long> qtdeEvento { get; set; }
        public string tipoEvento { get; set; }
        public string eKeyEvento { get; set; }
    
        public virtual tbCTeEventoDocument tbCTeEventoDocument { get; set; }
        public virtual tbCTeEventoProcess tbCTeEventoProcess { get; set; }
        public virtual tbCTeEventoRetorno tbCTeEventoRetorno { get; set; }
    }
}
