//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcteinut
    {
        public long idcte { get; set; }
        public long cnpjEmissor { get; set; }
        public long clientId { get; set; }
        public long erpCode { get; set; }
        public Nullable<short> serie { get; set; }
        public Nullable<long> counterid { get; set; }
        public Nullable<long> protocolNumber { get; set; }
        public Nullable<System.DateTime> processDate { get; set; }
        public string processMessage { get; set; }
        public short statusProcess { get; set; }
        public short statusCTe { get; set; }
        public byte[] xmlInut { get; set; }
        public string station { get; set; }
    
        public virtual tbcteRetornoInut tbcteRetornoInut { get; set; }
    }
}
