//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDefinition
    {
        public int id { get; set; }
        public string station { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string name { get; set; }
        public string fantasyName { get; set; }
        public decimal series { get; set; }
        public string addrName { get; set; }
        public decimal number { get; set; }
        public string complement { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string UF { get; set; }
        public string flagEnviaIENaoContrib { get; set; }
        public decimal tpImp { get; set; }
        public decimal tpAmb { get; set; }
        public string versionCTe { get; set; }
        public string versionMDFe { get; set; }
        public decimal procEmiCTe { get; set; }
        public decimal procEmiMDFe { get; set; }
        public string procVersionCTe { get; set; }
        public string procVersionMDFe { get; set; }
        public string modalCTe { get; set; }
        public string modalMDFe { get; set; }
        public string modCTe { get; set; }
        public string modMDFe { get; set; }
        public string directoryCTe { get; set; }
        public string directoryMDFe { get; set; }
        public string cancelMessageCTe { get; set; }
        public string cancelMessageMDFe { get; set; }
        public string inutMessageCTe { get; set; }
        public decimal tpEmitMDFe { get; set; }
        public string cUnidMDFe { get; set; }
        public string usuarioCriacao { get; set; }
        public System.DateTime dataCriacao { get; set; }
        public string usuarioAtualizacao { get; set; }
        public Nullable<System.DateTime> dataAtualizacao { get; set; }
        public string dataVigenciaIni { get; set; }
        public string dataVigenciaFim { get; set; }
        public string status { get; set; }
        public string descComboBox { get; set; }
    }
}
