//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstado
    {
        public short cdUF { get; set; }
        public string estado { get; set; }
        public string UF { get; set; }
    }
}
