//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLog
    {
        public int idLog { get; set; }
        public string tpDoc { get; set; }
        public string tpLog { get; set; }
        public string processMessage { get; set; }
        public string processDate { get; set; }
        public string processTime { get; set; }
    }
}
