//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmdfereceptionhistory
    {
        public string origemManifesto { get; set; }
        public string destinoManifesto { get; set; }
        public string numVoo { get; set; }
        public string dataVoo { get; set; }
        public byte[] documentData { get; set; }
        public string processDate { get; set; }
        public string processHHMM { get; set; }
        public string actionTag { get; set; }
        public string serie { get; set; }
        public string counterId { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<System.DateTime> statusDate { get; set; }
    }
}
