//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmdfedocument
    {
        public long idmdfe { get; set; }
        public byte[] documentData { get; set; }
        public byte[] documentMDFE { get; set; }
        public byte[] documentMDFECanc { get; set; }
        public byte[] documentMDFEEncer { get; set; }
        public Nullable<System.DateTime> sendingDate { get; set; }
        public Nullable<System.DateTime> interfaceSendingDate { get; set; }
    
        public virtual tbmdfe tbmdfe { get; set; }
    }
}
