//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmdfeprocess
    {
        public long idmdfe { get; set; }
        public Nullable<int> idActionType { get; set; }
    
        public virtual tbmdfe tbmdfe { get; set; }
    }
}
