//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmdfeRetorno
    {
        public long idmdfe { get; set; }
        public byte[] documentRetMDFE { get; set; }
        public string processDate { get; set; }
        public string processHHMM { get; set; }
        public Nullable<short> statusMDFe { get; set; }
        public string xmlRetornoDate { get; set; }
        public string xmlRetornoHHMM { get; set; }
    
        public virtual tbmdfe tbmdfe { get; set; }
    }
}
