//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMigrationFile1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMigrationFile1()
        {
            this.tbMigrationFile8 = new HashSet<tbMigrationFile8>();
        }
    
        public string ODN { get; set; }
        public string AWB_ID { get; set; }
        public string AirlineCode { get; set; }
        public string Issuance { get; set; }
        public string MAWB_Number { get; set; }
        public string Origin_Station { get; set; }
        public string Destination_Station { get; set; }
        public string Payment_Method { get; set; }
        public string Product_Code { get; set; }
        public string UTC_Creation { get; set; }
        public string Local_Creation { get; set; }
        public string Currency_Code { get; set; }
        public string Freight_Amount { get; set; }
        public string Fare_Amount { get; set; }
        public string Fare_Type { get; set; }
        public string Declared_Amount { get; set; }
        public string Insurance_Number { get; set; }
        public string Insurance { get; set; }
        public string Observation { get; set; }
        public string CFOPNumber { get; set; }
        public string User_Code_Creation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMigrationFile8> tbMigrationFile8 { get; set; }
    }
}
