//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMigrationFile8
    {
        public int ID { get; set; }
        public string OND { get; set; }
        public string AWB_ID { get; set; }
        public string ChaveCte { get; set; }
    }
}
