//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPostCode
    {
        public string bairro { get; set; }
        public string logradouro { get; set; }
        public int idMun { get; set; }
        public string CEP { get; set; }
    }
}
