//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int idUsuario { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public string nomeUsuario { get; set; }
        public string email { get; set; }
        public string dominio { get; set; }
        public System.DateTime dtCreate { get; set; }
        public string status { get; set; }
        public string dtIniVigencia { get; set; }
        public string dtfimVigencia { get; set; }
        public Nullable<System.DateTime> dtUpdate { get; set; }
        public string userUpdate { get; set; }
        public string userCreate { get; set; }
    }
}
